version: 2
defaults: &defaults
  working_directory: ~/supdock
  docker:
    - image: circleci/node:10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn check:typescript
      - run: yarn lint
      - run: yarn test
      - run: yarn compile
      - run: |
          yarn build:ci
          ./bin/supdock-linux --help
      - persist_to_workspace:
          root: ~/supdock
          paths:
            - bin
            - dist

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/supdock
      - run:
          name: 'GitHub release'
          command: |
            wget https://github.com/tcnksm/ghr/releases/download/v0.12.1/ghr_v0.12.1_linux_amd64.tar.gz
            tar -xzvf ghr_v0.12.1_linux_amd64.tar.gz
            VERSION=$(./bin/supdock-linux --version)
            ./ghr_v0.12.1_linux_amd64/ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} bin/ || true
      - run:
          name: 'NPM/yarn release'
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/supdock/dist/.npmrc
            yarn publish:ci || true

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
